### ISSUE TITLE
CI/CD 도입

### ISSUE THREAD

**Issue by totw5701** [totw5701/Idol-collector#31]
# Description

# ToDo List
- [x] CI travis-ci 로 자동 테스트 및 빌드
- [x] CI 빌드 파일 S3로 이동
- [x] CD 자동 배포
